[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[variables]
PORT = "8080"
NODE_ENV = "production"

[build.env]
NODE_VERSION = "18.x"

[[services]]
internal_port = 8080
protocol = "http"

[deploy.envs]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
PORT = "${PORT}"
NODE_ENV = "production"
FRONTEND_URL = "${FRONTEND_URL}"